---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_solo
  data_path: "test/fixtures"

platforms:
  - name: centos-6.4
  - name: ubuntu-12.04

suites:
  - name: server
    run_list:
      - recipe[jr-jenkins::server]

  - name: job
    run_list:
      - recipe[jr-jenkins::server]
      - recipe[jr-jenkins_job::update_no_verify]
