---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero
  data_path: test/fixtures
  data_bags_path: test/fixtures/data_bags

platforms:
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[jr-jenkins-test::default]
