language: ruby
rvm:
  - 1.9.3
bundler_args: --without kitchen_vagrant --without integration
before_script:
  - bundle exec berks install
script:
  - bundle exec foodcritic -f any .
  - bundle exec rubocop
